# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Omnivorous
tagline:             Adventures in Biomedical Data Science at Duke
url:                 http://omnivorous.gitub.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Erich S. Huang
  url:               https://twitter.com/erichhuang
  email:             erich.huang@duke.edu
  
# This is the list of pages to include in the header of the website.
pages_list:       
  About:             '/about/'

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/omnivorous/omnivorous.github.io
